version: "3.4"
services:
  traefik_init:
    image: traefik:1.5
    command:
      - "storeconfig"
      - "--api"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--acme"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.email=$EMAIL"
      - "--acme.storage=traefik/acme/account"
      - "--acme.OnHostRule=true"
      - "--acme.onDemand=false"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.exposedbydefault=true"
      - "--docker.domain=$DOMAIN"
      - "--docker.watch"
      - "--logLevel=DEBUG"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - hyperpaas
    deploy:
      labels:
        com.hyperpaas.internal: 'true'
      restart_policy:
        condition: on-failure
    depends_on:
      - consul

  traefik:
    image: traefik:1.5
    depends_on:
      - traefik_init
      - consul
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
      - "--acme.storage=traefik/acme/account"
    networks:
      - hyperpaas
    deploy:
      mode: global
      labels:
        com.hyperpaas.internal: 'true'
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s
      placement:
        constraints:
          - 'node.role == manager'
      update_config:
        parallelism: 1
        delay: 10s

  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt":true,"server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      labels:
        com.hyperpaas.internal: 'true'
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    networks:
      - hyperpaas

  registry:
    image: registry:2
    volumes:
      - registry-data:/var/lib/registry
    environment:
      - REGISTRY_AUTH="htpasswd"
      - REGISTRY_AUTH_HTPASSWD_PATH="/run/secrets/index.$DOMAIN.htpasswd"
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_STORAGE="filesystem"
      - REGISTRY_LOG_LEVEL="debug"
    deploy:
      replicas: 1
      labels:
        com.hyperpaas.internal: 'true'
        traefik.port: '5000'
        traefik.frontend.entryPoints: 'https'
        traefik.frontend.rule: 'Host:index.$DOMAIN'
        traefik.enable: 'true'
        traefik.docker.network: 'hyperpaas'
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    secrets:
      - registry.htpasswd
    networks:
      - hyperpaas

networks:
  hyperpaas:
    driver: overlay
    attachable: true
    labels:
      com.hyperpaas.internal: 'true'

volumes:
  consul-data:
      driver: local
      labels:
        com.hyperpaas.internal: 'true'
  registry-data:
      driver: local
      labels:
        com.hyperpaas.internal: 'true'

secrets:
  registry.htpasswd:
    external: true
