version: "3.2"
services:
  traefik:
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /Users/euskadi31/Projects/go-project/src/github.com/hyperscale/hyperpaas/var/lib/hyperpaas/traefik/
        target: /data
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    image: traefik:1.4.6
    command: [
      "traefik",
      "--defaultentrypoints=http,https",
      "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https",
      "--entryPoints=Name:https Address::443 TLS",
      "--acme",
      "--acme.entrypoint=https",
      "--acme.email=axel@etcheverry.biz",
      "--acme.storage=/data/acme.json",
      "--acme.ondemand=true",
      "--docker",
      "--docker.swarmmode",
      "--docker.exposedbydefault=true",
      "--docker.domain=traefik",
      "--docker.watch",
      "--web",
      "--logLevel=DEBUG"
    ]
    networks:
      - hyperpaas
    deploy:
      mode: global
      labels:
        com.hyperpaas.internal: 'true'
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s
      placement:
        constraints:
          - 'node.role == manager'
          - 'node.platform.os == linux'

networks:
  hyperpaas:
    driver: overlay
    attachable: true
